### ISSUE TITLE
problems with session handling in appgrid SDK

### ISSUE THREAD

**Issue by luisaccedo** [Accedo-Products/appgrid-sdk-js#8]
We are trying to use` getEntryById `method and it doesn't send session info to the server even though it has created session and save it to sessionStorage. We're working with the last version of chrome
First we are instantiating providing the app key `client = appgrid(appGridSettings);`
Then we are calling `getAppGridClient()` and then` getAllMetadata()`

Session is stored on the browser on sessionStorage under `ag_s` key but is not attached as X-Session on the headers nor as query string parameter

:S
 
thanks for the help 

best

**Comment by gouegd** [comment]
Hi Luis,

What is the `getAppgridClient` method ? I don't think it belongs to the SDK.
Could you possibly share the code, or even better, the repository ? If it is open to all accedo people, then I will have access to it.
Thanks,
Greg

**Comment by luisaccedo** [comment]
hi, 

Yes, you're right, that method is from viki, https://bitbucket.org/accedo/mediaset-play-web

**Comment by luisaccedo** [comment]
import appgrid from 'appgrid';

export const getAppGridClient = () => {
  const appGridSettings = getAppGridSettings();

  if (!appGridSettings) {
    return Promise.reject('No AppGrid settings available.');
  }

  if (!client) {
    client = appgrid(appGridSettings);
  }

  return Promise.resolve(client);
};

**Comment by luisaccedo** [comment]
can you reproduce the issue?

**Comment by luisaccedo** [comment]
appGridSettings is an object:
`{
 appKey:  "599dd33e1de1c4000df9c73d"
}`

**Comment by gouegd** [comment]
I've cloned and launched your app successfully.
I didn't see any call to get an entry, so I modified the code in configuration.js to get some more requests sent to appgrid:

```js
export const getAppGridConfig = () => {
  return getAppGridClient().then(client => {
    client.getEntries();
    client.getEntryById('59b9067d1de1c4000c9ad060');
    return client.getAllMetadata();
  }).catch(err => console.log(err));
};
```

I can see the requests in the devtool network panel (each call generates an OPTIONS call then a GET call).
Note the OPTIONS call does not get app-specific headers attached (like x-session), only the GET request does. Maybe you were looking at the OPTIONS request ?

Note the SDK ships with an `example-browser.html` file that you can play with and see successful requests to entries.

**Comment by luisaccedo** [comment]
we tried that and is not working for us :(

**Comment by gouegd** [comment]
Can you expand on this ? What is not working, what are you seeing, what have you tried ?

**Comment by ilgianfra** [comment]
Hi @gouegd 

It seems if you launch the application the really first time (so clear all the data and cache) there are 2 HTTP calls for the session key and metadata and status remain in OPTIONS then doesn't make the request.
But after the first launch the metadata and status got the response (sometimes).

Can you try again clearing all the data from the browser? and then refresh the page. It looks working time to time but not always.
![screen shot 2017-10-10 at 10 21 21](https://user-images.githubusercontent.com/11957418/31377050-21b364a6-ada7-11e7-9b25-aa1b713b179a.png)

**Comment by luisaccedo** [comment]
in my case this is what happens"
-cache disabled by chrome dev tools
-deleted all application data

the first time I refresh it makes 2 session requests (weird) and then metadata remains in options... (no  data fetched)

the second time I refresh it makes 1 session request (not sure if it should make one) and metadata request remains in options and no data is fetched

From this point every refresh has the same behaviour as second time

![screen shot 2017-10-10 at 10 32 40](https://user-images.githubusercontent.com/16936785/31377342-fa1297ae-ada7-11e7-859e-cb5769b2f54e.png)

**Comment by gouegd** [comment]
Hi @ilgianfra,

An OPTIONS call with 200 OK has to be followed by another request, as far as I understand.
I think you probably have filtered the requests to show 'XHR' only. The requests following an OPTIONS call do not appear in that category, you will see them if you filter on 'all' again (and, if you want, on the 'api.cloud' text)

**Comment by luisaccedo** [comment]
wow, we feel stupid, thank you for that

**Comment by luisaccedo** [comment]
so if I click all and then xhr again, I can see both calls

**Comment by luisaccedo** [comment]
and it has the x-session header...

**Comment by gouegd** [comment]
that's weird ! Sort of a UI bug of the debugger network tab. I was surprised the first time too.

**Comment by gouegd** [comment]
The double call to open a session is weird, I'll have a look at the code tomorrow (I'm in NZ, it's night already here). It is normal to open a session when you refresh, not to have it done twice.

**Comment by luisaccedo** [comment]
that only happens when we clean application data...

**Comment by luisaccedo** [comment]
thank you @gouegd !
